name: Bug report
description: File a bug about the project tooling or repository
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the project! Please describe the bug below.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: false
